
# folder path of dataset, which includes 2 subfolders: cloudy_image/ and ground_truth/
# data: WHUS2-CRv
# datasets_dir: ./data/RICE_DATASET/RICE1/
# train_list: train_list.txt
# test_list: test_list.txt
datasets_dir: ./data/RICE_DATASET/RICE1/
train_list: train_list.txt
test_list: test_list.txt

cuda: True
gpu_ids: [0, 1]

train_size: 0.8
validation_size: 0.2 # 验证集大小是占训练集的半分比
batchsize: 1
validation_batchsize: 1
epoch: 200
n_data: 433
width: 512
height: 512
threads: 0

lr: 0.0004
beta1: 0.5
lamb: 1
minimax: 1

gen_init: 
dis_init: 
in_ch: 3
out_ch: 3

manualSeed: 0
snapshot_interval: 1

nChannel: 3
nDenselayer: 10
nFeat: 64
growthRate: 32
